name = "FrequencyMaxwell"
uuid = "89bf6b0d-b02f-4c76-8a5d-868ec9be6234"
authors = ["Dohyeon Lee <dleh428@kaist.ac.kr>"]
version = "0.1.0"
description = "Modern Julia electromagnetic solver with automatic differentiation support"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
julia = "1.6"
LinearSolve = "2"
FFTW = "1.4"
StaticArrays = "1.5"
KernelAbstractions = "0.9"
SciMLBase = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[targets]
test = ["Test", "Zygote", "ChainRulesCore"]
